services:
  connector:
    image: ghcr.io/8xff/atm0s-media-server:master
    network_mode: "host"
    command: ["connector", "--mq-uri", "nats://nats:4222"]
    privileged: true
    profiles: [connector]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ./env/connector.env
  nats:
    profiles: [connector]
    hostname: nats
    image: nats:2.6.0
  gateway:
    image: ghcr.io/8xff/atm0s-media-server:master
    network_mode: "host"
    privileged: true
    profiles: [gateway, cluster]
    command: ["gateway"]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ./env/gateway.env
  rtmp:
    image: ghcr.io/8xff/atm0s-media-server:master
    network_mode: "host"
    privileged: true
    command: ["rtmp"]
    profiles: [rtmp, cluster]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ./env/rtmp.env
  token:
    image: ghcr.io/8xff/atm0s-media-server:master
    command: ["token-generate"]
    profiles: [token, cluster]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ./env/token.env
    ports:
      - 5000:5000
  webrtc:
    image: ghcr.io/8xff/atm0s-media-server:master
    network_mode: "host"
    profiles: [webrtc, cluster]
    privileged: true
    command: ["webrtc"]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ./env/webrtc.env
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
version: '3'

