name: atm0s-single-zone
services:
  console:
   image: ghcr.io/8xff/atm0s-media-server:master
   network_mode: "host"
   command: ["console"]
   labels:
    - "com.centurylinklabs.watchtower.enable=true"
   env_file:
    - ./env/console.env
    - ./env/shared.env
  gateway:
   image: ghcr.io/8xff/atm0s-media-server:master
   network_mode: "host"
   command: ["gateway"]
   labels:
    - "com.centurylinklabs.watchtower.enable=true"
   env_file:
    - ./env/gateway.env
    - ./env/shared.env
   depends_on:
     console:
      condition: service_started
  connector:
   image: ghcr.io/8xff/atm0s-media-server:master
   network_mode: "host"
   command: ["connector"]
   labels:
    - "com.centurylinklabs.watchtower.enable=true"
   env_file:
    - ./env/connector.env
    - ./env/shared.env
   depends_on:
     gateway:
      condition: service_started
  media:
   image: ghcr.io/8xff/atm0s-media-server:master
   network_mode: "host"
   command: ["media"]
   labels:
    - "com.centurylinklabs.watchtower.enable=true"
   env_file:
    - ./env/media.env
    - ./env/shared.env
   depends_on:
     gateway:
      condition: service_started
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
