version: '3'
services:
  connector:
    image: ghcr.io/8xff/atm0s-media-server:master
    network_mode: "host"
    command: ["connector", "--mq-uri", "nats://nats:4222"]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ../env/connector.env
  nats:
    image: nats:2.6.0
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
