version: '3'
services:
  webrtc:
    image: ghcr.io/8xff/atm0s-media-server:master
    network_mode: "host"
    privileged: true
    command: ["webrtc"]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ../env/webrtc.env
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
